name: Deploy Game
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pygbag
        run: pip install pygbag
      - name: Build Game
        run: python3 -m pygbag --build $GITHUB_WORKSPACE/main.py
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
